# Manual for `.yamllint.yaml` config:
# https://yamllint.readthedocs.io/en/stable/configuration.html
---
extends: default

yaml-files:
  - '*.yaml'
  - '*.yml'
  - '.yamllint'

rules:
  line-length:
    max: 120
  brackets:
    min-spaces-inside: 1
    max-spaces-inside: 1
  comments:
    min-spaces-from-content: 1
  new-lines:
    type: unix
